language: c

# Use newer travis container-based infrastructure
sudo: false

# Install flex dependency
addons:
  apt:
    packages:
      - flex
      - autoconf
      - libtool
      - automake
      - m4
      - aclocal-1.13

# Build using gcc and clang since it is supported
compiler:
  - clang
  - gcc

script: ./configure && make && make check && make distcheck && make CC=$CC -C c -f Makefile.no-autoconfig
